version: '3.8'
services:
  postgis:
    image: postgis/postgis:15-3.4
    container_name: task4-postgis
    environment:
      POSTGRES_DB: geom_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 10_QWERTy
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data: